#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-kpeg
Version  : 1.0.0
Release  : 7
URL      : https://rubygems.org/downloads/kpeg-1.0.0.gem
Source0  : https://rubygems.org/downloads/kpeg-1.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: rubygem-kpeg-bin
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc

%description
= kpeg
home :: https://github.com/evanphx/kpeg
bugs :: https://github.com/evanphx/kpeg/issues

%package bin
Summary: bin components for the rubygem-kpeg package.
Group: Binaries

%description bin
bin components for the rubygem-kpeg package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n kpeg-1.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-kpeg.gemspec

%build
gem build rubygem-kpeg.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
kpeg-1.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/kpeg-1.0.0
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/kpeg-1.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/.gemtest
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/bin/kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/calculator/calculator.kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/calculator/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/foreign_reference/literals.kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/foreign_reference/matcher.kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/foreign_reference/matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/lua_string/driver.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/lua_string/lua_string.kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/lua_string/lua_string.kpeg.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/phone_number/README.md
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/phone_number/phone_number.kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/phone_number/phone_number.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/upper/README.md
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/upper/upper.kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/examples/upper/upper.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/kpeg.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/hoe/kpeg.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/code_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/compiled_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/format_parser.kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/format_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/grammar.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/grammar_renderer.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/match.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/position.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/string_escape.kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/lib/kpeg/string_escape.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/test/inputs/comments.kpeg
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/test/test_kpeg.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/test/test_kpeg_code_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/test/test_kpeg_compiled_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/test/test_kpeg_format.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/test/test_kpeg_format_parser_round_trip.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/test/test_kpeg_grammar.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/test/test_kpeg_grammar_renderer.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/test/test_kpeg_string_escape.rb
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/vim/syntax_kpeg/ftdetect/kpeg.vim
/usr/lib64/ruby/gems/2.3.0/gems/kpeg-1.0.0/vim/syntax_kpeg/syntax/kpeg.vim
/usr/lib64/ruby/gems/2.3.0/specifications/kpeg-1.0.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/kpeg
